.bazelrc, .github/pull_request_template.md, .github/workflows/test-check-lint.yml, ci/lsan.supp, ci/lsan_hack.sh, tools/code_format/check_format.py
This PR adds the initial CI workflows necessary to ensure code quality.
* Add PR template.
* Add lsan scripts used with the building process.
* Add GitHub actions workflow to test, check, and lint the code.
Yes.
=> ci: add lint-tests-check ci workflow ( PROOF-605 )

sxt/multiexp/bucket_method/BUILD, sxt/multiexp/bucket_method/combination.cc, sxt/multiexp/bucket_method/combination.h, sxt/multiexp/bucket_method/combination.t.cc
Add the host function for the combination step of the bucket method.
A function for combining buckets
Yes.
=> feat: add function to combine buckets (PROOF-642)

.github/workflows/release.yml
Try to fix permissioning for release job.
Checkout code using the access token.
No. Will test when release job is run.
=> ci: fix release permissioning (PROOF-537)

flake.lock
Routine update of GPU driver for nix environment.
=> build: update gpu drivers (PROOF-642)

README.md
Update readme to include details about required environment for runtime.
Fixes #114
=> docs: add notes for installation

sxt/multiexp/pippenger2/multiexponentiation.h
Adds additional logging to better understand the performance of multiexponentiations.
=> feat: add additional logging for multiexponentiations (PROOF-831)

sxt/multiexp/pippenger2/multiexponentiation.h, sxt/multiexp/pippenger2/multiexponentiation.t.cc, sxt/multiexp/pippenger2/reduce.h, sxt/multiexp/pippenger2/reduce.t.cc
=> feat: add host support for packed multiexponentiations (PROOF-877)

STYLE.md, rust/blitzar-sys/README.md
Fixed typos for clarity in the documentation.
some typo corrections refine grammars
This is just docs text modify
=> docs: refine tests(typo, grammar)

nix/bazel.nix, sxt/base/log/BUILD
Clean up build by dropping unused options.
=> build: drop unused build options (PROOF-899)

sxt/algorithm/base/mapper.h, sxt/algorithm/base/reducer.h
=> chore: clean up concept definitions (PROOF-913)

cbindings/fixed_pedersen.t.cc, sxt/cbindings/backend/computational_backend.cc, sxt/cbindings/backend/computational_backend.h, sxt/cbindings/backend/cpu_backend.cc, sxt/cbindings/backend/cpu_backend.h, sxt/cbindings/backend/gpu_backend.cc, sxt/cbindings/backend/gpu_backend.h, sxt/multiexp/pippenger2/BUILD, sxt/multiexp/pippenger2/in_memory_partition_table_accessor.h
Fix cpu_backend so that it doesn't use pinned memory and hence doesn't require gpu drivers.
Switch the allocator used by cpu_backend.
Yes.
=> fix: don't use pinned memory in cpu_backend (PROOF-921)

sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/proof_computation.cc, sxt/proof/sumcheck/proof_computation.h, sxt/proof/sumcheck/proof_computation.t.cc
Construct sumcheck proofs.
Adds a component for constructing sumcheck proofs using a driver.
Yes.
=> feat: construct sumcheck proofs (PROOF-913)

sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/partial_polynomial_mapper.cc, sxt/proof/sumcheck/partial_polynomial_mapper.h, sxt/proof/sumcheck/partial_polynomial_mapper.t.cc, sxt/proof/sumcheck/polynomial_mapper.cc, sxt/proof/sumcheck/polynomial_mapper.h, sxt/proof/sumcheck/polynomial_mapper.t.cc
Polynomial mappers will be used to expand MLEs in the sum step of a GPU sumcheck proof.
Added components for mapping indexes to expanded MLEs.
Yes.
=> feat: add polynomial mappers (PROOF-913)

sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/constant.cc, sxt/proof/sumcheck/constant.h, sxt/proof/sumcheck/driver_test.cc, sxt/proof/sumcheck/driver_test.h, sxt/proof/sumcheck/gpu_driver.cc, sxt/proof/sumcheck/gpu_driver.h, sxt/proof/sumcheck/gpu_driver.t.cc
Adds a driver for creating sumcheck proofs using a GPU.
* A new component gpu_driver that provides a GPU implementation of the driver interface.
* Refactors driver tests so that they can be reused.
Yes.
=> feat: add sumcheck driver for GPU (PROOF-913)

README.md
Make readme file's sentences neat
some sentence missed the period
Actual this change is only fix the readme file's missing period
=> docs: Fix Missing Period at the End of a Sentence

flake.lock
Routine update of the build environment
=> build: update build environment (PROOF-913)

benchmark/reduce2/README.md
Refer to other. md docs, the title of the first paragraph should be the highest level
only upgrade the title level
only changed the .md file, no need to run test
=> docs: upgrade the title level

sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/sumcheck_random.cc, sxt/proof/sumcheck/sumcheck_random.h
Generate random sumcheck problems of given sizes.
This will be used to better test proof generation.
=> feat: generate random sumcheck problems (PROOF-913)

sxt/algorithm/base/mapper.h, sxt/algorithm/reduction/thread_reduction.h, sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/reduction_gpu.cc, sxt/proof/sumcheck/reduction_gpu.h, sxt/proof/sumcheck/reduction_gpu.t.cc
Add a component to reduce partially aggregated polynomials.
This will be used to support chunked sumcheck.
* Adds a new component for reducing polynomials
* Makes some tweaks to the Mapper concept to work around a limitation of clang and to make it useable in GPU code.
Yes
=> feat: reduce partially aggregated polynomials (PROOF-913)

sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/cpu_driver.cc, sxt/proof/sumcheck/proof_computation.t.cc
Add randomized sumcheck testing and fix folding in cpu driver.
* Test verification for random sumcheck problems
* Fixes folding in cpu_driver
Yes
=> fix: fix cpu_driver and add random testing (PROOF-913)

sxt/proof/sumcheck/BUILD, sxt/proof/sumcheck/chunked_gpu_driver.cc, sxt/proof/sumcheck/chunked_gpu_driver.h, sxt/proof/sumcheck/chunked_gpu_driver.t.cc, sxt/proof/sumcheck/proof_computation.cc, sxt/proof/sumcheck/proof_computation.t.cc
Add a driver to support chunked sumcheck.
* Adds a new chunked gpu driver component
Yes
=> feat: add chunked driver for sumcheck (PROOF-913)

cbindings/backend.cc, sxt/multiexp/pippenger/exponent_aggregates_computation.cc, sxt/scalar25/operation/reduce.t.cc
Follows up on https://github.com/spaceandtimelabs/blitzar/pull/234 to fix typos
=> refactor: fix typos

benchmark/sumcheck/benchmark.m.cc
Adds a verification check to sumcheck benchmark.
The verification has minimal overhead and can help to identify any issues.
Modifies sumcheck benchmark to do an additional verification check.
Yes, I've been testing benchmarks locally.
=> chore: add verification step to benchmark (PROOF-913)
