spaceandtimefdn/blitzar

- .github/workflows/test-check-lint.yml
- ci/build.sh
- rust/blitzar-sys/Cargo.toml
- rust/blitzar-sys/build.rs
- rust/tests/Cargo.toml
The Blitzar shared library needs to be downloaded by the Rust sys crate during the build process. This approach is better than building the library each time, which would be unfeasible as this process requires many dependencies.
* Update the Rust build script to build the Blitzar shared library locally under version 0.0.0 (only used with CI and tests).
* Update the Rust build script to download the Blitzar shared library from the GitHub release when the version is not 0.0.0.
* Update CI to test this build.
Only the local build is tested. The shared lib download will be tested in a consecutive PR.
> ci: update rust build script to download shared lib from github releases ( PROOF-603 )

- .github/workflows/release.yml
- .github/workflows/test-check-lint.yml
- ci/build.sh
- package.json
We need to properly version the blitzar code. For that, we use semantic-release with the guidelines highlighted [here](https://github.com/spaceandtimelabs/blitzar/blob/main/CONTRIBUTING.md#-commit-message-guidelines). Assets are published to both GitHub releases and crates.io during this process. 
* Add semantic-release workflow to CI. It only executes during merges to main.
* Push the Blitzar sys crate, the Blitzar shared library, and the header file to GitHub releases.
* Publish the blitzar sys-crate to crates.io. Note: The sys crate downloads the shared library from GitHub releases during building time.
* Add a step to test the published crate.
No. We'll see the results after the code is merged into the main.
> feat: setup semantic release and crates.io publishing ( PROOF-609 )

- README.md
- ci/docker/Dockerfile
- ci/docker/install_bazel.sh
- ci/docker/install_buildifier.sh
- ci/docker/install_clang_format.sh
- ci/docker/install_rust.sh
- ci/docker/run_docker_cpu.sh
- ci/docker/run_docker_gpu.sh
- ci/docker/setup_build_environment.sh
This PR adds the docker file scripts, necessary to build the development docker image `spaceandtimelabs/blitzar`.
* Only add the dockerfile and the auxiliary bash scripts.
No need.
> ci: add docker files to repo ( PROOF-615 )

- sxt/multiexp/multiproduct_gpu/kernel.h
The clang-18 compiler fails when compiling relocatable device code with dynamically allocated shared memory passed through a lambda expression ([see issue](https://github.com/llvm/llvm-project/issues/65806)). This situation happens in the `multiexp/multiproduct_gup:kernel` component.
In order to switch the compiler to clang-18, we need to use the a work around. The work around is to pass an object that points to the dynamically allocated shared memory object. This should be a temporary change while the clang compiler bug is still open.
* The function passed a dynamically allocated shared memory object in the `multiexp/multiproduct_gup:kernel` component is now passed an object that points to the dynamically allocated shared memory object
Yes, from previous tests with additional benchmark …
> ci: add clang rdc compilation error workaround to multiexp kernel component ( PROOF-630 )

- sxt/cbindings/backend/computational_backend.h
- sxt/cbindings/backend/cpu_backend.h
- sxt/cbindings/backend/gpu_backend.h
- sxt/curve21/operation/scalar_multiply.h
- sxt/curve_g1/operation/cmov.h
- sxt/curve_g1/operation/mul_by_3b.h
- sxt/field12/base/arithmetic_utility.t.cc
- sxt/multiexp/pippenger/driver.h
- sxt/multiexp/pippenger/exponent_aggregates_computation.h
- sxt/multiexp/pippenger/multiproduct_table.h
- sxt/proof/inner_product/cpu_workspace.h
- sxt/proof/inner_product/driver.h
- sxt/proof/inner_product/proof_computation.h
- sxt/proof/inner_product/workspace.h
- sxt/proof/transcript/transcript_primitive.h
- sxt/ristretto/operation/add.h
- sxt/ristretto/operation/scalar_multiply.h
- sxt/seqcommit/generator/base_element.h
When building with the clang compiler, we get various code warnings. Fixing these code warnings will help the code base and can be done before the compiler is updated to clang. This PR addresses code updates needed to get rid of the warnings issued from the clang compiler.
* multiple struct/class instance renaming
* integer literal converted to hex in test component
Yes, from previous tests.
> ci: clean up code related clang warnings ( PROOF-635 )

- .github/workflows/release.yml
- .github/workflows/test-check-lint.yml
- ci/docker/run_docker_cpu.sh
- ci/docker/run_docker_gpu.sh
- ci/docker/setup_build_environment.sh
The build environment for the Docker image should be updated to add `clang-18` as a compiler option.
What still needs done:
- `clang-18` is now also installed in the `ci/docker/setup_build_environment.sh` shell script.
- `spaceandtimelabs/blitzar:12.2.0-cuda-1.71.1-rust-1` has been built.
- The tag has been updated in the appropriate files.
Yes
> Draft: ci: add clang-18 to Docker image env setup ( PROOF-633 )

- sxt/proof/inner_product/generator_fold.cc
Fix bug that appears with full optimizations. I was using the incorrect value when doing a bit shift.
A fix for bug.
Functionality is covered under existing tests. I'm going to follow up with a PR that runs tests with full optimizations in the CI.
> fix: fix decompose_generators_fold (PROOF-620)

- rust/blitzar-sys/Cargo.toml
This PR removes the Rust version requirement of at least 1.71.1 from the Cargo.toml file for the Blitzar-sys crate.
* Remove the Rust version restriction.
No.
> build: drop unnecessary rust version restriction ( PROOF-625 )

- bazel/sxt_build_system.bzl
- sxt/multiexp/multiproduct_gpu/multiproduct_computation_descriptor.h
In switching to clang, I missed an option in the build that is skipping all of the tests.
* Add missing alwayslink option so that tests can run
* Fix a warning that clang gives.
Yes.
> build: fix tests (PROOF-620)

- sxt/curve_g1/operation/BUILD
- sxt/curve_g1/operation/add.cc
- sxt/curve_g1/operation/add.h
- sxt/curve_g1/operation/add.t.cc
In order to perform MSM with elements on the G1 curve, the element concept in `sxt/base/curve/element` requires an `add_inplace` function be implemented. The `add_inplace` implementation is similar to the `add` function with different parameters and two less temporary variables. 
- The `add_inplace` is added to the `add` component in the `curve_g1/operations` package.
- The `add` function is refactored to use the `add_inplace` implementation internally.
Yes
> feat: add_inplace should be implemented in the curve_g1 package ( PROOF-663 )

- .github/workflows/test-check-lint.yml
- sxt/execution/async/awaiter.cc
- sxt/execution/async/awaiter.h
- sxt/execution/async/coroutine_promise.cc
- sxt/execution/async/coroutine_promise.h
- sxt/execution/async/future.cc
- sxt/execution/async/future.h
- sxt/execution/async/promise.cc
- sxt/execution/async/promise.h
- sxt/execution/device/computation_event.cc
- sxt/execution/device/computation_event.h
Nvlink crashes when using `extern templates`. I put in https://developer.nvidia.com/bugs/4288496 and Nvidia should be on track to fix in a future toolkit release. In the meantime, I'm commenting out the cases where we use `extern template`.
Disabling `extern template`.
Reuses existing tests. Additionally, I re-enabled some test that were failing to build without the workaround.
> fix: workaround to nvlink bug (PROOF-642)

- cbindings/BUILD
libblitzar.so is failing to load in some environments because the libm isn't linked.
Add "-lm" to the linker flags.
Our CI environment doesn't appear to have the problem, but verified the fix on an environment that gives the loading error.
> fix: link math library (PROOF-0000)

- sxt/curve_g1/operation/BUILD
- sxt/curve_g1/operation/compression.cc
- sxt/curve_g1/operation/compression.h
- sxt/curve_g1/operation/compression.t.cc
- sxt/curve_g1/type/BUILD
- sxt/curve_g1/type/compressed_element.cc
- sxt/curve_g1/type/compressed_element.h
- sxt/curve_g1/type/compressed_element.t.cc
- sxt/field12/property/BUILD
- sxt/field12/property/lexicographically_largest.cc
- sxt/field12/property/lexicographically_largest.h
- sxt/field12/property/lexicographically_largest.t.cc
Projective elements in the `curve_g1` package group should be able to support compression. Compressed elements will be used as the output of MSM. Compression means only the `X` value of an affine element is retained. The `Y` value can later be derived from the `X` value and bit flags set during serialization. The serialization of the compressed value follows the serialization outlined in the [librustzcash](https://github.com/zcash/librustzcash/blob/6e0364cd42a2b3d2b958a54771ef51a8db79dd29/pairing/src/bls12_381/README.md#serialization) project.
- Most significant bit - indicates if the element is compressed
- Second-most significant bit - indicates if the element is a point at infinity
- Third-most significant significant - indicates if the `Y` value of the element is lexicographically …
> feat: the G1 curve should support element compression ( PROOF-664 )

- cbindings/blitzar_api.h
- cbindings/get_generators.cc
- cbindings/get_generators.t.cc
- cbindings/get_one_commit.cc
- cbindings/get_one_commit.t.cc
- cbindings/inner_product_proof.cc
- cbindings/inner_product_proof.t.cc
- cbindings/pedersen.cc
- cbindings/pedersen.t.cc
- example/cbindings1/main.cc
- rust/tests/src/main.rs
Now that blitzar will begin supporting multiple curves, the C function signatures in the `blitzar_api` component should follow the naming convention of projects like [libsodium](https://github.com/jedisct1/libsodium). The naming convention is  `<project>_<curve>_<type or function>`. 
We can change this naming convention in the future to include another identifier if our project ever grows to the point where we would want another level of hierarchy.
Note the blitzar-rs project will also have to update to respect the API changes.
- The functions and structs in the `blitzar_api` component now follow the `<project>_<curve>_<type or function>` naming convention.
Yes
> refactor!: update api function signatures to support multiple curves ( PROOF-701 )

- sxt/base/iterator/index_range.cc
- sxt/base/iterator/index_range.h
- sxt/base/iterator/index_range_utility.cc
- sxt/base/iterator/index_range_utility.t.cc
- sxt/multiexp/curve/multiexponentiation.h
Currently, large computations can fail if they require too much GPU memory, and smaller computations can run inefficiently if we try to split them across multiple GPUs and the coordination overhead is greater than the parallelization benefit.
This PR adds the capability to specify min and max chunk sizes for an index range to give us greater control over how computations are split. This is similar to what Intel's TBB library provides: https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Controlling_Chunking_os.html.
* Add ability to specify min/max chunk sizes for an index range
* Put in some ballpark min/max chunk sizes for multiexponentiation.
Yes.
> feat: support min/max chunk sizes (PROOF-642)

- sxt/execution/device/device_viewable.h
- sxt/execution/device/test_kernel.cc
- sxt/memory/management/managed_array.h
- sxt/memory/management/managed_array.t.cc
- sxt/multiexp/curve/naive_multiproduct_solver.h
- sxt/multiexp/multiproduct_gpu/multiproduct.t.cc
- sxt/multiexp/pippenger/multiproduct_decomposition_gpu.cc
- sxt/multiexp/pippenger/multiproduct_decomposition_kernel.cc
- sxt/multiexp/pippenger/test_driver.cc
- sxt/proof/inner_product/gpu_driver.cc
- sxt/scalar25/operation/inner_product.cc
- sxt/scalar25/operation/inner_product.t.cc
Add a resize method to memmg::manged_array to make code easier to read and more convenient to write.
* Add resize method to memmg::managed_array
* Adds some documentation for memmg::manged_array
* Refactors existing code to use resize method
Yes.
> feat: add a resize method to memmg::managed_array (PROOF-642)

- .bazelrc
- sxt/base/functional/function_ref.h
- sxt/proof/inner_product/gpu_driver.cc
Minor clean ups of code and build.
* Replace std::result_of with std::invoke_result since std::result_of is deprecated and removed in c++20: https://en.cppreference.com/w/cpp/types/result_of
* Fix compiler warning for unused variable
* Drop -stdlib=libstdc++ from c++ options as it's the default for our build environment anyways.
Uses existing tests.
> chore: minor code and build clean ups (PROOF-642)

- nix/bazel.nix
Adds git to bazel's path -- it's needed to download dependencies.
Minor tweaks to bazel wrapepr script.
Pending.
> fix: fix issues with nix environment (PROOF-537)

- bazel/sxt_build_system.bzl
- sxt/base/curve/BUILD
- sxt/base/num/log2p1.h
- sxt/base/num/log2p1.t.cc
- sxt/multiexp/bucket_method/BUILD
- sxt/multiexp/bucket_method/combination_kernel.cc
- sxt/multiexp/bucket_method/combination_kernel.h
- sxt/multiexp/bucket_method/combination_kernel.t.cc
Add kernels for the combination steps of the bucket method. These roughly map to operations from algorithm 1 of https://eprint.iacr.org/2022/999.pdf.
This PR is part of support better multi-exponentiation.
* A component combination_kernel with functions for combining buckets and bucket groups.
* Extended log2p1 to include a consteval version.
Yes.
> feat: combination step of bucket method (PROOF-642)

- README.md
The text on the Blitzar logo does not appear on light backgrounds. 
This PR adds a logo that can be displayed on light backgrounds and updates the HTML to detect if the color scheme is light or dark.
Note, this is a companion PR to one in the `blitzar-rs` project: https://github.com/spaceandtimelabs/blitzar-rs/pull/10.
- The image link is updated to default to the dark logo.
- A `<picture>` tag is added to detect dark/light color schemes in Github's markdown following [this post](https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/).
Yes.
> ci: add dark Blitzar logo ( PROOF-680 )

- rust/blitzar-sys/Cargo.toml
- rust/blitzar-sys/README.md
The `blitzar-sys` crate should have a basic README that provides users information and links to the main components of the Blitzar project.
- A README.md file is added to the `blitzar-sys` Rust project.
Yes with VSCode's markdown viewer but not on crates.io.
> ci: add blitzar-sys README to crates.io ( PROOF-637 )

- sxt/multiexp/bucket_method/BUILD
- sxt/multiexp/bucket_method/accumulation.cc
- sxt/multiexp/bucket_method/accumulation.h
- sxt/multiexp/bucket_method/accumulation.t.cc
Add a function to accumulate the generators for a multi-exponentiation into buckets. The function is invoked from the host and splits work across available GPUs.
This PR  builds on  #45 and is part of making multi-exponentiation perform better.
A  new function for bucket accumulation.
Yes.
> feat: add host-side bucket accumulation function (PROOF-642)

- cbindings/pedersen.t.cc
Remove usage of [variable length arrays](https://en.wikipedia.org/wiki/Variable-length_array#:~:text=In%20computer%20programming%2C%20a%20variable,value%20(see%20Dependent%20type).), which aren't valid c++ and trigger a warning.
Rewrites test code to not use variable length arrays.
Yes.
> chore: fix compiler warnings (PROOF-537)

- cbindings/pedersen.t.cc
Fix more variable length array warnings.
Follow up from https://github.com/spaceandtimelabs/blitzar/pull/52
> chore: remove more variable length arrays (PROOF-537)

- sxt/memory/resource/BUILD
- sxt/memory/resource/chained_resource.cc
- sxt/memory/resource/chained_resource.h
- sxt/memory/resource/chained_resource.t.cc
- sxt/memory/resource/counting_resource.cc
- sxt/memory/resource/counting_resource.h
Winking out can make code simpler and faster when used correctly. See https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0089r1.pdf for reference.
This PR adds a memory resource suitable for winked out host or device allocations.
* Adds chained_resource that tracks allocations and deallocates everything upon destruction.
* Adds counting_resource as a tool for testing custom resources.
Yes
> feat: add chained_resource to support winked out allocations (PROOF-716)

- sxt/base/field/BUILD
- sxt/base/field/element.cc
- sxt/base/field/element.h
- sxt/base/field/example_element.cc
- sxt/base/field/example_element.h
- sxt/base/field/example_element.t.cc
- sxt/base/field/subtract_p.h
The `base/field` package now has an `element` concept and a minimal `example_element` component. The `element` concept will allow field operations done with elements in Montgomery form to be written generically. These field operations currently exist in the `field12` package group and depend on the `f12t::element`.
- An `element` concept is added to the `base/field` package that is similar to the `base/curve/element` concept.
- A minimal `example_element` component is added to the `base/field` package that is similar to the `base/curve/example_element` component.
- Branching is removed from the `base/field/subtract_p` component.
Yes
> feat: add element concept to base field package ( PROOF-748 )

- sxt/base/container/BUILD
- sxt/base/container/span.h
- sxt/base/container/span_utility.h
- sxt/base/container/span_utility.t.cc
- sxt/base/type/BUILD
- sxt/base/type/value_type.cc
- sxt/base/type/value_type.h
- sxt/base/type/value_type.t.cc
- sxt/memory/management/managed_array.h
Minor enhancements to make our containers more align with standard library containers and easier to work with.
* Add value_type as a member to our container classes.
* Add bast::value_type_t alias to retrieve the value type of a container.
* Add winked_span to make it easier to make winked allocations.
Yes
> feat: minor enhancements to container types (PROOF-716)

- sxt/execution/device/BUILD
- sxt/execution/device/device_copy.cc
- sxt/execution/device/device_copy.h
- sxt/execution/device/device_copy.t.cc
- sxt/execution/device/device_viewable.h
- sxt/execution/device/device_viewable.t.cc
Add routines to make managing device memory easier.
* extended make_active_device_viewable to support winked allocation
* added a routine for a winked copy of memory to the active device
Yes
> feat: async memory management (PROOF-716)

- sxt/seqcommit/test/test_generators.cc
Drop usage of VLAs as they are a c only feature.
> chore: fix variable-length-array warnings (PROOF-537)

- .github/workflows/test-check-lint.yml
- flake.lock
- flake.nix
- nix/shell.nix
Migrates most of the CI jobs to use nix. There's still the rust test and the release script to migrate.
* Switch ci jobs from docker to nix
Tests run in CI.
> ci: migrate to use nix (PROOF-537)

- sxt/base/num/BUILD
- sxt/base/num/abs.cc
- sxt/base/num/abs.h
- sxt/base/num/abs.t.cc
- sxt/base/type/int.h
- sxt/multiexp/pippenger/BUILD
- sxt/multiexp/pippenger/exponent_aggregates_computation.cc
- sxt/multiexp/pippenger/multiproduct_decomposition_kernel.cc
- sxt/multiexp/pippenger/multiproduct_table.cc
- sxt/multiexp/test/BUILD
- sxt/multiexp/test/curve21_arithmetic.cc
- sxt/multiexp/test/multiexponentiation.cc
Support commitments of signed 128-bit integers.
* added a custom `abs` function that works on 128-bit integers
* refactored host and GPU code to work on 128-bit integers
Yes. I extended the multiexponentiation tests to cover cases with signed 128-bit integers.
> feat: support commitments of signed 128-bit integers (PROOF-772)

- sxt/field25/type/BUILD
- sxt/field25/type/element.cc
- sxt/field25/type/element.h
- sxt/field25/type/element.t.cc
- sxt/field25/type/literal.cc
- sxt/field25/type/literal.h
- sxt/field25/type/literal.t.cc
In order to support MSM with elements on the `bn254` curve we need to implement the base field `Fq`. This work will introduce the type package and components to the `bn254` base field, `field25`. The components are copied from the the `field12/type` package, which supports the `bls12-381` curve. The components are updated to support the `bn254` base field, which is four limbs, compared to the six limbs of the `bls12-381` base field.
The only non-trivial code change, which updated the limbs from six to four, is isolated to [this commit](https://github.com/spaceandtimelabs/blitzar/commit/6f02083b4609741640cc801b8e43fceeb5fa756e).
- The `element` and `literal` components are copied from the `field12/type` package and updated to support the four limbs.
Yes
> feat: add field25 type package (PROOF-775)

- sxt/field25/operation/BUILD
- sxt/field25/operation/cmov.cc
- sxt/field25/operation/cmov.h
- sxt/field25/operation/cmov.t.cc
- sxt/field25/operation/invert.cc
- sxt/field25/operation/invert.h
- sxt/field25/operation/invert.t.cc
- sxt/field25/operation/pow_vartime.cc
- sxt/field25/operation/pow_vartime.h
- sxt/field25/operation/pow_vartime.t.cc
- sxt/field25/operation/square.cc
- sxt/field25/operation/square.h
- sxt/field25/operation/square.t.cc
In order to support MSM with elements on the `bn254` curve we need to implement the base field `Fq`. This work will introduce cmov, inversion, pow, and square components to the `bn254` base field, `field25`. The components are copied from the the `field12` package, which supports the `bls12-381` curve. The components are updated to support the `bn254` base field, which is four limbs, compared to the six limbs of the `bls12-381` base field.
All non-trivial changes are isolated to [this commit](https://github.com/spaceandtimelabs/blitzar/commit/a663fa8e482fca0c1ebf0f7e5d604a0d5f3e04d5).
- `cmov`, `invert`, `pow_vartime`, and `square` components are copied from `field12` and updated to support four limbs.
- Tests are updated.
Yes
> feat: add cmov, invert, pow, and square components to field25 operation package (PROOF-778)

- sxt/curve_bng1/type/BUILD
- sxt/curve_bng1/type/compressed_element.cc
- sxt/curve_bng1/type/compressed_element.h
- sxt/curve_bng1/type/compressed_element.t.cc
- sxt/curve_bng1/type/conversion_utility.cc
- sxt/curve_bng1/type/conversion_utility.h
- sxt/curve_bng1/type/conversion_utility.t.cc
- sxt/curve_bng1/type/element_affine.cc
- sxt/curve_bng1/type/element_affine.h
- sxt/curve_bng1/type/element_affine.t.cc
- sxt/curve_bng1/type/element_p2.cc
- sxt/curve_bng1/type/element_p2.h
- sxt/curve_bng1/type/element_p2.t.cc
- sxt/curve_bng1/type/operation_adl_stub.cc
- sxt/curve_bng1/type/operation_adl_stub.h
In order to support MSM with `G1` elements on the `bn254` curve we need to implement a curve package. This work introduces the `bn254` `G1` curve and type package along with the type components. The components are copied from the `curve_g1/type` package, which supports the `bls12-381` curve. The components are updated to support the `bn254` base field, which is four limbs, compared to the six limbs of the `bls12-381` base field.
Non-trivial changes are isolated to [this commit](https://github.com/spaceandtimelabs/blitzar/commit/03c4ab339cfaea047babf3c90b06595126946656).
- A new package to support the `bn256` `G1` curve, `curve_bng1`, is added to the `sxt` package group.
- A `type` package and components are copied from the `curve_g1/type` package.
- The components in the `curve_bng1/type` …
> feat: add bn254 G1 curve and type package (PROOF-780)

- sxt/curve_bng1/operation/BUILD
- sxt/curve_bng1/operation/add.cc
- sxt/curve_bng1/operation/add.h
- sxt/curve_bng1/operation/add.t.cc
- sxt/curve_bng1/operation/neg.cc
- sxt/curve_bng1/operation/neg.h
- sxt/curve_bng1/operation/neg.t.cc
- sxt/curve_bng1/operation/scalar_multiply.cc
- sxt/curve_bng1/operation/scalar_multiply.h
- sxt/curve_bng1/operation/scalar_multiply.t.cc
In order to support MSM with `G1` elements on the `bn254` curve we need to implement the curve package. This work will introduce the `add`, `neg`, and `scalar_multiply` to the `bn254` operation package. The components are copied from the `curve_g1/operation` package, which supports the `bls12-381` curve. The components are updated to support the `bn254` `G1` curve.
Non-trivial changes are isolated to [this commit](https://github.com/spaceandtimelabs/blitzar/commit/5701fdcae321b2ec8d561bcb419d0f5fd046eda4).
- `add`, `neg`, and `scalar_multiply` components and tests are copied from `curve_g1/operation` and updated to support `bn254` `G1` curve elements.
Yes
> feat: add, neg, and scalar_multiply components are added to bn254 G1 curve package (PROOF-739)

- cbindings/blitzar_api.h
- rust/blitzar-sys/Cargo.toml
- rust/blitzar-sys/build.rs
Running `cargo doc` will produce a number of warnings. This work addresses these warnings and adds a doc link to the `blitzar-sys` crate. Further improvements to the documentation formatting are planned for future PRs.
Additionally, the docs are not building on crates.io ([see build log](https://docs.rs/crate/blitzar-sys/1.30.0/builds/1101919)).
```
[INFO] [stderr]    Compiling blitzar-sys v1.30.0 (/opt/rustwide/workdir)
[INFO] [stderr] error: failed to run custom build command for `blitzar-sys v1.30.0 (/opt/rustwide/workdir)`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/blitzar-sys-5f78313fd9924058/build-script-build` (exit status: 1)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   Error: reqwest::Error { …
```
> doc: address cargo doc warnings and build error (PROOF-786)

- cbindings/blitzar_api.h
In an effort to improve documentation, formatting has been updated in the `blitzar_api.h` file. No text has been rewritten, only formatting to improve readability on crates.io.
- Formatting has been updated throughout `blitzar_api.h`.
Yes, locally using `cargo doc`.
> docs: format the Rust docs (PROOF-786)

- sxt/proof/inner_product/gpu_driver.cc
There is a bug in the inner product proof where a coroutine is being destroyed while memory it owns is still referenced.
Change inner product gpu driver to not destroy coroutine early.
Ran tests locally, but will also try to test on a multi-gpu machine where the issue is reproduced more consistently.
> fix: fix bug in inner product proof (PROOF-788)

- sxt/algorithm/block/BUILD
- sxt/algorithm/block/runlength_count.cc
- sxt/algorithm/block/runlength_count.h
- sxt/algorithm/block/runlength_count.t.cc
Add an algorithm that counts the run lengths of sorted items across a block of threads.
This will be used to compute the multi-product table of a multiexponentiation.
The coded is written in the style of Nvidia's CUB library.
* Add package group for algorithms that operate on thread blocks
* Add a component for the runlength algorithm.
Yes.
> feat: add runlength count algorithm (PROOF-642)

- sxt/multiexp/base/BUILD
- sxt/multiexp/base/scalar_array.cc
- sxt/multiexp/base/scalar_array.h
- sxt/multiexp/base/scalar_array.t.cc
Add a function that will copy and transpose scalar exponents into device memory.
This will be used as part of the bucket method.
* Add a new component that creates an array of transposed scalars
Yes.
> feat: add function to copy and transpose scalars into device memory (PROOF-642)

- sxt/multiexp/bucket_method2/BUILD
- sxt/multiexp/bucket_method2/multiproduct_table.cc
- sxt/multiexp/bucket_method2/multiproduct_table.h
- sxt/multiexp/bucket_method2/multiproduct_table.t.cc
- sxt/multiexp/bucket_method2/multiproduct_table_kernel.cc
- sxt/multiexp/bucket_method2/multiproduct_table_kernel.h
- sxt/multiexp/bucket_method2/multiproduct_table_kernel.t.cc
Compute the multi-product table for a version of the bucket method that better handles many outputs.
* Added a component to compute the multiproduct table for the bucket method.
Yes.
> feat: compute multiproduct table for bucket method (PROOF-642)

- sxt/multiexp/bucket_method2/BUILD
- sxt/multiexp/bucket_method2/reduce.cc
- sxt/multiexp/bucket_method2/reduce.h
- sxt/multiexp/bucket_method2/reduce.t.cc
Add a component for the reduction step of the bucket method when the multi-exponentiation has a large number of outputs.
* A new component for the bucket method reduction step.
Yes.
> feat: add code for the reduction step of a bucket method with many outputs (PROOF-642)

- sxt/curve_bng1/random/BUILD
- sxt/curve_bng1/random/element_p2.cc
- sxt/curve_bng1/random/element_p2.h
- sxt/curve_bng1/random/element_p2.t.cc
- sxt/curve_g1/random/BUILD
- sxt/curve_g1/random/element_p2.cc
- sxt/curve_g1/random/element_p2.h
- sxt/curve_g1/random/element_p2.t.cc
Random element generators are needed to run benchmarks on curve addition primitives. This work adds random element generators to the `bn254` and `bls12-381` curves.
The random element is generated by generating a random scalar and multiplying the number by the curve's generator. Note, the random scalar does not respect the modulus of the curve's scalar field. This is okay for benchmarks, but not for secure random element generation. The scalar field packages have not been implemented yet.
- A `random` component is added to both the `curve_g1` and `curve_bng1` packages.
Yes.
> feat: add random element generators to bls12-381 and bn254 curves (PROOF-511)

- benchmark/primitives/BUILD
- benchmark/primitives/README.md
- benchmark/primitives/benchmark.m.cc
- benchmark/primitives/curve_ops_bls12_381.cu
- benchmark/primitives/curve_ops_bls12_381.h
- benchmark/primitives/field_ops_bls12_381.cu
- benchmark/primitives/field_ops_bls12_381.h
- benchmark/primitives/stats.cc
- benchmark/primitives/stats.h
Measuring primitive performance inside of Blitzar will help us identify where to focus improvement efforts. This work adds primitive benchmarks for `bls12-381` curve addition, field addition, and field multiplication inside of Blitzar.
A follow up PR will add primitive benchmarks for the `bn254` curve.
- A new benchmark package is added, `primitives`.
- Files to support measuring curve addition, field addition, and field multiplication for `bls12-381` elements are added.
Yes
> bench: add bls12-381 primitive benchmarks (PROOF-804)

- benchmark/primitives/BUILD
- benchmark/primitives/README.md
- benchmark/primitives/benchmark.m.cc
- benchmark/primitives/curve_ops_bn254.cu
- benchmark/primitives/curve_ops_bn254.h
- benchmark/primitives/field_ops_bn254.cu
- benchmark/primitives/field_ops_bn254.h
Measuring primitive performance inside of Blitzar will help us identify where to focus improvement efforts. This work adds primitive benchmarks for `bn254` curve addition, field addition, and field multiplication inside of Blitzar.
- Files to support measuring curve addition, field addition, and field multiplication for `bn254` elements are added.
Yes
> bench: add bn254 primitive benchmarks (PROOF-804)

- sxt/field12/operation/BUILD
- sxt/field12/operation/neg.cc
- sxt/field12/operation/neg.h
In an effort to improve the performance of MSM with the `bls12-381` and `bn254` curve elements, field operation optimizations have been identified in the base field packages. This work is part of the performance improvements. The base field `neg` operation component is inlined. Results from primitive benchmarks, which is an average of three different GPU benchmarks (Single T4 VM, Multi T4 VM, and GeForce RXT 3080) GPU indicate that inlining the base field `neg` operation provides:
From previous performance PR (PROOF-823)
Curve ops
- 1.09x speed up of `bls12-381` curve addition from PROOF-823
- 1.04x speed up of `bn254` curve addition from PROOF-823
Field ops
- 1.08x speed up of `bls12-381` field addition from PROOF-823
- 1.02x speed up of `bn254` field addition from PROOF-823
- 1.01x slow …
> feat: inline neg in the field12 and field25 base packages (PROOF-824)

- sxt/base/bit/BUILD
- sxt/base/bit/count.h
- sxt/base/bit/permutation.cc
- sxt/base/bit/permutation.h
- sxt/base/bit/permutation.t.cc
When making a table of precomputed values for the partition step of Pippenger's algorithm, it's useful to be able to iterate over all permutations with a given number of bits set to 1. This PR adds a low level function to provide this capability.
* A function for iterating over bit permutations
* Modify count_trailing_zeros to work for smaller integral types.
Yes.
> feat: add a function to iterate over bit permutations (PROOF-831)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/partition_table.cc
- sxt/multiexp/pippenger2/partition_table.h
- sxt/multiexp/pippenger2/partition_table.t.cc
Compute the table of precomputed sums used in the Pippenger partition step
Add a component for computing the partition table.
Yes.
> feat: compute table of partition sums (PROOF-831)

- app/blitzar/BUILD
- app/blitzar/main.cc
Add utility to create the table of precomputed generator sums used in the partition step of Pippenger's algorithm. The table is written to a file. In the next phases of the work, I'll be adding algorithms that can use the file of precomputed sums to compute multiexponentiations.
Note: The utility is only for curve25519, right now. I plan to add options to work with the other curves in follow on PRs.
Add a command line utility for creating the partition table. It includes future proofing so that the utility can be extended to perform other functions if required.
Most of the functionality uses existing components that are unit tested. I did some manual testing and will add more testing as the rest of the code is built out.
> feat: add utility for creating table of precomputed sums (PROOF-831)

- sxt/base/test/BUILD
- sxt/base/test/temp_file.cc
- sxt/base/test/temp_file.h
- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.cc
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.t.cc
- sxt/multiexp/pippenger2/partition_table_accessor.cc
- sxt/multiexp/pippenger2/partition_table_accessor.h
Add an interface and accessor for the precomputed sums used in the partition step of Pippenger's algorithm.
Note: This might get extended in the future to have accessors that go from a file to GPU memory so that it's not necessary to hold all of the precomputed sums in host memory.
* Add an interface an in-memory implementation of a partition table accessor.
* Add utilities for testing with files
Yes
> feat: add interface accessor for partition table sums (PROOF-831)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.t.cc
- sxt/multiexp/pippenger2/partition_product.cc
- sxt/multiexp/pippenger2/partition_product.h
- sxt/multiexp/pippenger2/partition_product.t.cc
Compute the multi product product of scalars using an accessor to precomputed products for groups of 16 generators.
* Add component to compute the multi-product for the bits of a scalar array.
* Fix interpretation of the offset argument in in_memory_partition_table_accessor
Yes
> feat: add component for computing product of partitions (PROOF-831)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.cc
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.t.cc
In order to make testing and benchmarking easier, this PR adds a utility function to create an in-memory accessor to precomputed partition sums given a span of generators. 
* A function to create an in memory partition table accessor.
Yes
> feat: add utility to create an in memory partition table accessor (PROOF-831)

- sxt/multiexp/pippenger2/partition_product.h
- sxt/multiexp/pippenger2/partition_product.t.cc
Fix termination condition for partition_product loop to properly abort when n is a multiple of 16.
Modify loop to abort when n is reduced to 16.
Yes. I added a test case with n=16.
> fix: fix partition product when n is a multiple of 16 (PROOF-831)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/reduce.cc
- sxt/multiexp/pippenger2/reduce.h
- sxt/multiexp/pippenger2/reduce.t.cc
Add component to reduce multi-products to a multi-exponentiation.
* A function for Pippener reductions.
Yes
> feat: add component for reduction step of multi-exponentiation (PROOF-831)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/multiexponentiation.cc
- sxt/multiexp/pippenger2/multiexponentiation.h
- sxt/multiexp/pippenger2/multiexponentiation.t.cc
Add a component to compute multiexponentiations using Pippenger's partition algorithm and precomputed generator sums.
A new component for computing multiexponentiations.
Yes.
> feat: add multiexponentiation function for Pippenger's partition method (PROOF-831)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/combination.cc
- sxt/multiexp/pippenger2/combination.h
- sxt/multiexp/pippenger2/combination.t.cc
Add a function to combine partial results of a multi-product. This will be used to make a multi-gpu version of the Pippenger partition step algorithm.
Adds a new component for combining partial multi-product results.
Yes
> feat: add component for combining partial multi-product results (PROOF-831)

- sxt/curve_bng1/operation/BUILD
- sxt/curve_bng1/operation/mul_by_3b.cc
- sxt/curve_bng1/operation/mul_by_3b.h
- sxt/curve_g1/operation/BUILD
- sxt/curve_g1/operation/mul_by_3b.cc
- sxt/curve_g1/operation/mul_by_3b.h
- sxt/field12/operation/neg.h
- sxt/field25/operation/BUILD
- sxt/field25/operation/neg.cc
- sxt/field25/operation/neg.h
In an effort to improve performance of curve operations for the pairing friendly curves, the `mul_3b` and `neg` components should be inlined. 
This PR improves the performance of curve addition by 1.06x.
- The `mul_3b` components for `curve_g1` and `curve_bng1` packages are inlined.
- The `neg` component is inlined in the `field24` package. It is already inlined in the `field12` package.
- A loop is unrolled in the `neg` component.
Yes
> perf: inline mul_3b and neg components (PROOF-851)

- sxt/base/iterator/index_range.cc
- sxt/base/iterator/index_range.h
- sxt/base/iterator/index_range_utility.cc
- sxt/base/iterator/index_range_utility.t.cc
When splitting the partition step of Pippenger's algorithm into smaller chunks, we want ensure chunks are a multiple of 16 the precomputed sums are done in groups of 16 generators.
This PR adds the capability to set a chunk multiple to an index_range to support enforcing a chunk multiple. 
Support specifying a chunk multiple for index ranges.
Yes
> feat: support specifying chunk multiples (PROOF-831)

- benchmark/multi_exp_pip/benchmark.m.cc
- cbindings/BUILD
- cbindings/backend.cc
- cbindings/fixed_pedersen.t.cc
- sxt/cbindings/backend/BUILD
- sxt/cbindings/backend/cpu_backend.cc
- sxt/cbindings/backend/gpu_backend.cc
- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/constants.cc
- sxt/multiexp/pippenger2/constants.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.t.cc
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.t.cc
- sxt/multiexp/pippenger2/multiexponentiation.h
- sxt/multiexp/pippenger2/multiexponentiation.t.cc
- sxt/multiexp/pippenger2/partition_product.h
- sxt/multiexp/pippenger2/partition_product.t.cc
- sxt/multiexp/pippenger2/partition_table.h
- sxt/multiexp/pippenger2/partition_table.t.cc
- sxt/multiexp/pippenger2/partition_table_accessor.h
- sxt/multiexp/pippenger2/reduce.h
- sxt/multiexp/pippenger2/reduce.t.cc
Support computing multiexponentiations using Pippenger's partition algorithm for the host side. This is the cpu version of https://github.com/spaceandtimelabs/blitzar/pull/130
* add cpu versions of Pippenger algorithms
* add more documentation
* minor renaming
* minor changes to make testing easier
Yes
> feat: add host support for multiexponentiations using precomputed partition method (PROOF-831)

- sxt/cbindings/backend/BUILD
- sxt/cbindings/backend/computational_backend.cc
- sxt/cbindings/backend/computational_backend.h
- sxt/cbindings/backend/cpu_backend.cc
- sxt/cbindings/backend/cpu_backend.h
- sxt/cbindings/backend/gpu_backend.cc
- sxt/cbindings/backend/gpu_backend.h
- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
Rework cpu backend so that it doesn't use pinned memory. Pinned memory requires that CUDA drivers be up-to-date which makes the library less portable. And if the GPU isn't available there's no benefit for it anyways.
Customize computational backend so that it only uses pinned memory for the gpu backend.
Yes
> feat: don't use pinned memory for cpu backend (PROOF-831)

- benchmark/multi_exp_pip/benchmark.m.cc
- sxt/cbindings/backend/cpu_backend.cc
- sxt/cbindings/backend/gpu_backend.cc
- sxt/cbindings/base/curve_id_utility.h
- sxt/cbindings/base/curve_id_utility.t.cc
This PR updates curve25519 to use a more compact point form for its partition table accessor. Benchmarking shows this improves multiexponentiation performance by ~20%.
Updates GPU and CPU backends and benchmark to use the compact point form for curve25519.
Reuses existing tests.
> feat: use a more compact point form for curve-25519's partition sum table (PROOF-870)

- benchmark/multi_exp_pip/benchmark.m.cc
- sxt/cbindings/base/curve_id_utility.h
- sxt/curve_g1/type/BUILD
- sxt/curve_g1/type/compact_element.cc
- sxt/curve_g1/type/compact_element.h
- sxt/curve_g1/type/element_p2.cc
- sxt/curve_g1/type/element_p2.h
- sxt/curve_g1/type/element_p2.t.cc
Make multiexponentiation more memory efficient for bls12-381
* adds a compact point for for bls12-381 elements. This is similar to element_affine but is written so that it doesn't need an extra boolean to identity the identity element.
* updates the multiexponentiation code to use the bls12-381 compact elements
Yes
> feat: update multiexponentiation code to use compact point form for BLS12-381 (PROOF-870)

- sxt/base/num/BUILD
- sxt/base/num/round_up.cc
- sxt/base/num/round_up.h
- sxt/base/num/round_up.t.cc
- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/partition_product.h
- sxt/multiexp/pippenger2/partition_product.t.cc
In the new packed interface, the number of products may not be a multiple of 8. This PR reworks the partition_product component so that num_products doesn't need to be a multiple of 8.
* Adds a component round_up to round a number up to the next nearest multiple.
* Refactors partition_product so that num_products doesn't need to be a multiple of 8.
Yes
> feat: rework partition product so that num_products doesn't need to be a multiple of 8 (PROOF-877)

- sxt/field25/operation/square.cc
The `square` component has an extra multiply and carry call setting the `t[7]` value. Luckily the `t[7]` value is set to the correct value a few lines later, avoiding a bug. This PR removes the unnecessary setting of `t[7]`.
- Setting the `t[7]` values with both `mac` output and the carry output is removed.
Yes
> fix: avoid extra step value setting in field25 square component (PROOF-883)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/reduce.h
- sxt/multiexp/pippenger2/reduce.t.cc
In order to support a more efficient interface for outputs of varying bit size, we need to do reductions with varying bit sizes.
This PR adds a version of reduce that can work with outputs of different bit lengths.
* Adds a new reduce function that takes a bit size table.
Yes
> feat: compute reductions for packed multi-exponentiations (PROOF-877)

- sxt/field12/type/BUILD
- sxt/field12/type/element.cc
- sxt/field12/type/element.h
- sxt/field25/type/BUILD
- sxt/field25/type/element.cc
- sxt/field25/type/element.h
- sxt/field51/type/BUILD
- sxt/field51/type/element.h
`CUDA_CALLABLE` is not needed on `constexpr` functions.
- `CUDA_CALLABLE` is removed from `constexpr` functions.
- The `CUDA_CALLABLE` header is removed from element components.
- `field12` and `field25` element components now use `std::equal` to verify equality.
Yes
> chore: remove CUDA_CALLABLE from constexpr functions (PROOF-890)

- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
- sxt/multiexp/pippenger2/partition_table.h
- sxt/multiexp/pippenger2/partition_table.t.cc
In order to experiment with different window widths for partition tables and perhaps find values that lead to better performance, this PR makes the window width an option when creating partition tables instead of fixing it to 16.
* rework functions to creating partition tables to accept a window width argument
Yes
> feat: support creating partition tables with different window widths (PROOF-893)

- flake.lock
In an effort to keep blitzar up-to-date, the nixpkgDrv should be updated to point to the latest Nvidia driver.
- The Nvidia driver now points to driver version 555.58.
Yes, locally on a system with the 555.58 driver.
> build: update nixpkgsDrv to use Nvidia driver version 555.58 (PROOF-894)

- cbindings/fixed_pedersen.t.cc
- sxt/cbindings/backend/BUILD
- sxt/cbindings/backend/cpu_backend.cc
- sxt/cbindings/backend/gpu_backend.cc
In the cbindings for packed multiexponentiations with generators, the size of the scalars span is calculated incorrect.
Correct the scalar size computation in the GPU and CPU backends.
Yes
> fix: fix size calculation in bindings (PROOF-877)

- tools/code_format/build_fixer.py
- tools/code_format/check_format.py
- tools/code_format/common.py
- tools/code_format/copyright_fixer.py
- tools/code_format/header_order.py
- tools/code_format/paths.py
Update the format scripts so that they use the version of python3 in PATH.
This makes the scripts more portable to environments where python3 isn't in /usr/bin/
* Modifies the #! path in various scripts.
Tested locally.
> build: make format scripts use the version of python3 available in PATH (PROOF-000)

- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.t.cc
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.t.cc
Benchmarking indicates that a smaller window width for the partition algorithm give better performance. This PR changes the default window width from 16 to 13.
* Update default parameters to use 13 instead of 16
* Rework the file system persistence code to store the window width.
Yes
> feat: change default partition window width (PROOF-893)

- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
Follow up to #159 . Benchmarking on additional servers indicates the change from 16 -> 13 may have been too large and resulted a performance decrease in some cases. This PR attempts a more moderate adjustment to 15.
> feat: change window size default for multiexponentiation algorithm (PROOF-893)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/variable_length_partition_product.cc
- sxt/multiexp/pippenger2/variable_length_partition_product.h
- sxt/multiexp/pippenger2/variable_length_partition_product.t.cc
Add a version of partition product that support variable lengths. This will be used to make a multi-exponentiation function that's more efficient for varying lengths.
* Adds a new component with partition product function that works for products with varying lengths 
* Minor refactoring of existing code to be usable in more contexts.
Yes
> feat: add a version of partition product that supports varying lengths (PROOF-896)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/variable_length_computation.cc
- sxt/multiexp/pippenger2/variable_length_computation.h
- sxt/multiexp/pippenger2/variable_length_computation.t.cc
Add a function to compute the lengths of products in a variable length multiexponentiation.
This will be used to build a more efficient function for multiexponentiation of varying lengths.
Adds a component with a function to fill in product lengths.
Yes
> feat: compute product lengths for variable length multiexponentiations (PROOF-896)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/multiexponentiation_options.cc
- sxt/multiexp/pippenger2/multiexponentiation_options.h
- sxt/multiexp/pippenger2/variable_length_multiexponentiation.cc
- sxt/multiexp/pippenger2/variable_length_multiexponentiation.h
- sxt/multiexp/pippenger2/variable_length_multiexponentiation.t.cc
Add multi-exponentiation functions that are more efficient for variable length problems.
This uses a simple implementation that I'm sure can be improved quite a bit. But the benchmarking shows it still leads to significant improvements (~30%) for triangularly structured multi-exponentiations.
Adds new multi-exponentiation functions.
Yes
> feat: add variable length multiexponentiation (PROOF-896)

- WORKSPACE
- bazel/libbacktrace/BUILD
- bazel/libbacktrace/backtrace-supported.h
- bazel/libbacktrace/config.h
- bazel/libbacktrace/libbacktrace.BUILD
- tools/code_format/check_format.py
Simplify the bazel build by dropping the foreign rules dependency for libbacktrace. This makes it easier to update the build environment. I plan to follow up with an additional PR to remove foreign rules completely.
> build: simplify build for libbacktrace (PROOF-899)

- WORKSPACE
- bazel/spdlog.BUILD
Drops foreign rules dependency to simplify the build environment.
> build: drop foreign_rules dependency (PROOF-899)

- app/blitzar/main.cc
- bazel/libbacktrace/libbacktrace.BUILD
- sxt/base/log/BUILD
- sxt/multiexp/pippenger2/in_memory_partition_table_accessor.h
* make some minor tweaks to fix code that errors on the latest version of clang
* set `linkstatic=1` attribute to make build faster.
> chore: minor changes for build update (PROOF-899)

- cbindings/BUILD
- cbindings/backend.cc
Support specifying the backend via an environmental variable
* add code to override default backend with the environmental variable BLITZAR_BACKEND
* panic if the GPU backend is selected but no GPUs are available
* add additional logging
Yes. Tested locally.
> feat: support specifying backend via an environmental variable(PROOF-903)

- .github/workflows/release.yml
- .github/workflows/test-check-lint.yml
The CI workflow will fail to find `nix` sometimes, causing the CI to fail. This PR sources `nix` before calling things like `nix develop`.
- The workflow now sources `nix` before calling `nix`.
Yes
> ci: source nix before develop call in workflow (PROOF-912)

- sxt/proof/inner_product/gpu_driver.cc
Fix multi-exponentiation function call so that it doesn't leave a dangling reference.
Rewrite function call to not leave a dangling refer
The code is covered in existing tests, but reliable reproduce the problem. I'll try to follow up with some changes to the address sanitizer build to see if it can be made to detect these types of errors.
> fix: fix lifetime issue in inner product multi-exponentiation (PROOF-914)

- README.md
- nix/cuda.nix
- sxt/algorithm/block/BUILD
- sxt/algorithm/block/runlength_count.h
- sxt/base/device/BUILD
- sxt/base/device/cub.cc
- sxt/base/device/cub.h
- sxt/multiexp/base/BUILD
- sxt/multiexp/base/scalar_array.cc
- sxt/multiexp/bucket_method2/BUILD
- sxt/multiexp/bucket_method2/multiproduct_table.cc
- sxt/multiexp/bucket_method2/multiproduct_table_kernel.h
The NVIDIA drivers required to run the CUDA toolkit 12.6 cannot be installed on Kubernetes clusters successfully. The version that can be installed is 550, which corresponds to [CUDA toolkit 12.4](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html). This PR downgrades the CUDA toolkit.
Downgrading the CUDA toolkit with the version of clang we are using causes the following error:
```
In file included from external/local_cuda/cuda/include/cub/cub.cuh:62:
In file included from external/local_cuda/cuda/include/cub/device/device_adjacent_difference.cuh:42:
In file included from external/local_cuda/cuda/include/cub/device/dispatch/dispatch_adjacent_difference.cuh:40:
In file included from external/local_cuda/cuda/include/cub/agent/agent_adjacent_difference.cuh:46:
In file …
```
> build: downgrade CUDA toolkit (PROOF-916)

- cbindings/BUILD
- cbindings/blitzar_api.h
- cbindings/fixed_pedersen.cc
- cbindings/fixed_pedersen.t.cc
- sxt/cbindings/backend/BUILD
- sxt/cbindings/backend/computational_backend.cc
- sxt/cbindings/backend/computational_backend.h
Add API functions to read and write multiexponentiation handles to disk.
With these functions, it can be significantly cheaper to create handles.
* Add sxt_multiexp_handle_new_from_file and sxt_multiexp_handle_write_to_file to blitzar_api.h.
Yes.
> feat: support serialization of multiexponentiation handles (PROOF-920)

- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/transcript_utility.cc
- sxt/proof/sumcheck/transcript_utility.h
- sxt/proof/sumcheck/transcript_utility.t.cc
Add functions for doing basic sumcheck operations on transcripts.
Adds a new component transcript_utility.
Yes.
> feat: add functions for doing basic sumcheck operations on transcripts (PROOF-913)

- .github/workflows/release.yml
- .github/workflows/test-check-lint.yml
The CI will sometimes fail if the `proofs-dev-muti-gpu-becnhmarks-w3` VM is on. It shows up as shared with the repository because it is in the same runner group as the the VM we want to use - `public-blitzar-T4-gpu-vm`. Since `proofs-dev-muti-gpu-becnhmarks-w3` is shared with the repository, there is no way to my knowledge or permissions level to remove it. This PR makes explicit in the workflow that we want to use `public-blitzar-T4-gpu-vm` as the runner.
- The workflow now is explicitly told to run on the `public-blitzar-T4-gpu-vm` self-hosted runner.
Yes
> ci: the runner should be specified in the workflow

- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/polynomial_utility.cc
- sxt/proof/sumcheck/polynomial_utility.t.cc
- sxt/proof/sumcheck/verification.cc
- sxt/proof/sumcheck/verification.h
- sxt/proof/sumcheck/verification.t.cc
Adds the verification step of sumcheck.
* Adds a component verification for verifying sumcheck
* Makes a fix to polynomial_utility to correctly compute 0-1 sum.
Yes
> feat: add verification step of sumcheck (PROOF-913)

- sxt/memory/management/managed_array.h
- sxt/memory/management/managed_array.t.cc
Add a constructor to support creating a managed_array from two iterators. This is a convenience constructor and matches what's available in other standard containers such as std::vector.
* Adds new constructor to managed_array that takes two iterators.
Yes
> feat: support constructing arrays from iterators (PROOF-913)

- cbindings/blitzar_api.h
There is a typo in the `blitzar_api` related to the `SXT_CURVE_GRUMPKIN` curve ID. It was the same as the `SXT_CURVE_BN_254` curve ID. This has not been a problem because `blitzar-rs` does not support grumkin yet.
- The `SXT_CURVE_GRUMPKIN` curve ID value is updated to be unique.
No, there are only tests for `SXT_CURVE_RISTRETTO255` curve elements. Future work should include tests for the other supported curves, including grumpkin,
> fix: the grumpkin curve ID in the blitzar_api should be unique

- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/cpu_driver.cc
- sxt/proof/sumcheck/cpu_driver.h
- sxt/proof/sumcheck/cpu_driver.t.cc
- sxt/proof/sumcheck/driver.cc
- sxt/proof/sumcheck/driver.h
- sxt/proof/sumcheck/polynomial_utility.cc
- sxt/proof/sumcheck/polynomial_utility.h
- sxt/proof/sumcheck/polynomial_utility.t.cc
- sxt/proof/sumcheck/workspace.cc
- sxt/proof/sumcheck/workspace.h
Add code for doing basic sumcheck operations for cpu.
These operations will be invoked when creating a sumcheck proof.
* adds a driver interface for doing the computational parts of sumcheck
* implements driver for cpu
Yes.
> feat: add sumcheck operations for cpu (PROOF-913)

- sxt/cbindings/backend/computational_backend_utility.cc
- sxt/cbindings/backend/computational_backend_utility.t.cc
- sxt/multiexp/pippenger2/variable_length_computation.cc
- sxt/multiexp/pippenger2/variable_length_computation.h
- sxt/multiexp/pippenger2/variable_length_computation.t.cc
- sxt/multiexp/pippenger2/variable_length_multiexponentiation.h
Fix an overflow when counting the number of products in a variable length multi-exponentiation.
* Use a 64-bit integer instead of a 32-bit integer when counting products.
Yes.
> fix: fix overflow in variable length multiexponentiation (PROOF-922)

- sxt/base/device/BUILD
- sxt/base/device/pinned_buffer.cc
- sxt/base/device/pinned_buffer.h
- sxt/base/device/pinned_buffer.t.cc
- sxt/base/device/pinned_buffer_handle.cc
- sxt/base/device/pinned_buffer_handle.h
- sxt/base/device/pinned_buffer_pool.cc
- sxt/base/device/pinned_buffer_pool.h
- sxt/base/device/pinned_buffer_pool.t.cc
Benchmarking shows that allocating pinned memory can be expensive. This PR adds a pool so that pinned allocations can be minimized.
I'll follow up with memory utility functions to make used of the pooled buffers and benchmarking for memory operations.
Adds a pinned buffer pool and a pinned buffer class to easily manage the acquisition and release of pooled buffers.
Yes.
> feat: add pinned buffer pool (PROOF-923)

- sxt/scalar25/operation/inner_product.cc
- sxt/scalar25/operation/inner_product.t.cc
Fix inner product so that it doesn't chunk inner products that are already in device memory
Changes inner product so that it doesn't chunk when inputs are already in device memory.
Without this change, some of the tests flake on machines with multiple GPUs.
Yes
> fix: don't split inner products that are already on device memory (PROOF-923)

- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/combine_reduce.cc
- sxt/multiexp/pippenger2/combine_reduce.h
- sxt/multiexp/pippenger2/combine_reduce.t.cc
- sxt/scalar25/operation/inner_product.t.cc
Chunk the combination and reduction of multi-exponentiation partials.
Using these functions, we'll be able to do reductions that are too large to fit into GPU memory.
* Adds a new component for doing chunked reductions of multi-exponentiation partials.
Yes
> feat: chunk combination of multiexponentiation partials (PROOF-923)

- sxt/multiexp/pippenger2/combine_reduce.h
- sxt/multiexp/pippenger2/combine_reduce.t.cc
Support combination reductions with fixed size outputs.
This change will support migrating multiexponentiations to used chunked reductions.
* Add a new combine_reduce function for outputs of fixed size.
Yes
> feat: support fixed size reductions (PROOF-923)

- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/device_cache.cc
- sxt/proof/sumcheck/device_cache.h
- sxt/proof/sumcheck/device_cache.t.cc
Add a device cache for sumcheck values reused between rounds.
This will be used to support a chunked version of sumcheck.
* Adds a component device_cache to manage sumcheck values cached on a device.
Yes
> feat: add cache for sumcheck values (PROOF-913)

- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/mle_utility.cc
- sxt/proof/sumcheck/mle_utility.h
- sxt/proof/sumcheck/mle_utility.t.cc
Add a utility component to copy partial slices of MLEs to and from device memory.
This will be used to support chunked sumcheck.
Adds a new component for copying partial MLEs
Yes
> feat: add utilities for copying partially computed sumcheck results (PROOF-913)

- sxt/execution/device/copy.cc
- sxt/execution/device/copy.t.cc
This rolls back the changes to strided copy.
The changes were mostly motivated by getting better code reuse; but it looks like I missed something that's causing certain multiexponentiations to break.
I'll do more testing and revisit those changes sometime later.
> fix: roll back changes to strided copy (PROOF-926)

- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/fold_gpu.cc
- sxt/proof/sumcheck/fold_gpu.h
- sxt/proof/sumcheck/fold_gpu.t.cc
Add a component for chunked folds.
This will be used to produce a chunked version of sumcheck.
* Adds a component for chunked folding.
Yes
> feat: add chunked sumcheck fold (PROOF-913)

- sxt/cbindings/backend/gpu_backend.cc
- sxt/multiexp/pippenger2/BUILD
- sxt/multiexp/pippenger2/multiexponentiation_serialization.h
- sxt/multiexp/pippenger2/multiexponentiation_serialization.t.cc
Follow up to #237 . Adds serialization support for more multiexponentiation APIs.
* extends serialization for packed multi-exponentiations.
Yes
> feat: support serializing packed multi-exponentiations (PROOF-927)

- README.md
The extra `</a>` tags were creating an incorrect HTML structure, causing potential issues in rendering. This fix ensures that each anchor (`<a>`) tag correctly wraps its respective image (`<img>`) tag, improving the HTML structure and ensuring proper functionality.
Removed the extra `</a>` closing tags from each badge link section to restore correct HTML structure.
This change does not directly require tests since it involves fixing HTML structure, but it ensures that the page renders correctly without breaking any functionality.
> docs: Fix incorrect closing tags in badge links

- tools/code_format/check_format.py
The `normalize_path` function was incorrectly adding `./` to paths that were already absolute (starting with `/`). This resulted in malformed paths like `.//usr/local/bin`, which could cause issues in path handling.
The fix ensures that absolute paths are not modified incorrectly, maintaining proper functionality for both relative and absolute paths.  
- Updated the `normalize_path` function to check if the path starts with either `./` or `/` before adding `./`.  
- This ensures that absolute paths remain unchanged, while relative paths are still normalized correctly.  
Yes, the changes have been tested to ensure they handle both relative and absolute paths correctly. Existing tests have been updated, and new test cases have been added to cover absolute path scenarios.
> chore: fix path normalization to handle absolute paths correctly

- sxt/multiexp/pippenger2/multiexponentiation.h
- sxt/multiexp/pippenger2/multiexponentiation.t.cc
From a previous PR, I accidentally left in some code that I was using for testing that breaks chunked multi-exponentiations.
This PR undoes that change.
Fixes #241 
* Removes a co_return statement I used for testing.
Yes. I added additional test cases for the area of code that was missed.
> fix: fix chunked multi-exponentiation (PROOF-926)

- sxt/multiexp/pippenger2/in_memory_partition_table_accessor_utility.h
- sxt/multiexp/pippenger2/multiexponentiation_serialization.h
Make reading serialized multi-exponentiations easier and add metadata in plain text.
* Small refactoring of in memory data accessor utility
* Add a meta.txt file to a multi-exponentiation serialization.
Reuses existing tests.
> feat: improvements to serialization (PROOF-927)

- cbindings/BUILD
- cbindings/blitzar_api.h
- cbindings/sumcheck.cc
- cbindings/sumcheck.h
- cbindings/sumcheck.t.cc
- sxt/cbindings/backend/BUILD
- sxt/cbindings/backend/callback_sumcheck_transcript.cc
- sxt/cbindings/backend/callback_sumcheck_transcript.h
- sxt/cbindings/backend/computational_backend.cc
- sxt/cbindings/backend/computational_backend.h
- sxt/cbindings/backend/cpu_backend.cc
- sxt/cbindings/backend/cpu_backend.h
- sxt/cbindings/backend/gpu_backend.cc
- sxt/cbindings/backend/gpu_backend.h
- sxt/cbindings/base/BUILD
- sxt/cbindings/base/field_id.cc
- sxt/cbindings/base/field_id.h
- sxt/cbindings/base/field_id_utility.cc
- sxt/cbindings/base/field_id_utility.h
- sxt/cbindings/base/field_id_utility.t.cc
- sxt/cbindings/base/sumcheck_descriptor.cc
- sxt/cbindings/base/sumcheck_descriptor.h
- sxt/proof/sumcheck/proof_computation.cc
Add C API for generating sumcheck proofs.
Extend blitzar_api.h with a new function sxt_prove_sumcheck for creating sumcheck proofs.
Yes.
> feat: add c api for proving sumcheck (PROOF-913)

- nix/shell.nix
Upgrade rust. 
The release job requires a newer version of rust.
> build: bump rust version (PROOF-913)

- cbindings/blitzar_api.h
- sxt/cbindings/backend/cpu_backend.cc
- sxt/cbindings/backend/gpu_backend.cc
- sxt/cbindings/base/BUILD
- sxt/cbindings/base/field_id.h
- sxt/cbindings/base/field_id_utility.h
- sxt/fieldgk/operation/BUILD
- sxt/fieldgk/operation/muladd.cc
- sxt/fieldgk/operation/muladd.h
- sxt/fieldgk/realization/BUILD
- sxt/fieldgk/realization/field.cc
- sxt/fieldgk/realization/field.h
- sxt/fieldgk/type/BUILD
- sxt/fieldgk/type/element.h
- sxt/fieldgk/type/operation_adl_stub.cc
- sxt/fieldgk/type/operation_adl_stub.h
- sxt/proof/sumcheck/BUILD
- sxt/proof/sumcheck/cpu_driver.h
- sxt/proof/sumcheck/proof_computation.t.cc
- sxt/proof/transcript/BUILD
- sxt/proof/transcript/transcript_primitive.h
- sxt/proof/transcript/transcript_utility.cc
- sxt/proof/transcript/transcript_utility.h
- sxt/proof/transcript/transcript_utility.t.cc
Support using grumpkin field with sumcheck.
* Small modifications to fieldgk to support field concept.
* Add transcript operations for fieldgk
Yes
> feat: add sumcheck support for grumpkin curve (PROOF-913)

- sxt/execution/async/BUILD
- sxt/execution/async/coroutine.h
- sxt/execution/async/coroutine.t.cc
- sxt/execution/async/shared_future.cc
- sxt/execution/async/shared_future.h
- sxt/execution/async/shared_future.t.cc
- sxt/execution/async/shared_future_state.cc
- sxt/execution/async/shared_future_state.h
- sxt/execution/async/shared_future_state.t.cc
Add a shared_future that can be awaited multiple times.
This is adopted from https://docs.seastar.io/master/classseastar_1_1shared__future.html
shared_future will be used to improve the GPU scheduling.
* Adds a shared_future class that can be awaited multiple times.
Yes
> feat: add shared future (PROOF-928)

- sxt/execution/async/future.h
- sxt/execution/async/future.t.cc
If a ready future is continued, the continuation future should also be ready.
* Fix continuations for futures that are already ready.
Yes.
> fix: fix future continuation for ready futures (PROOF-928)

- sxt/base/device/split.cc
- sxt/base/device/split.h
- sxt/base/device/split.t.cc
Determine chunk size based on available device memory.
Adds a function to determine split options from available device memory.
Yes
> feat: chunk based on available device memory (PROOF-928)

- sxt/base/device/pinned_buffer.cc
- sxt/base/device/pinned_buffer.h
- sxt/base/device/pinned_buffer.t.cc
- sxt/execution/device/BUILD
- sxt/execution/device/copy.cc
- sxt/execution/device/copy.t.cc
- sxt/execution/device/generate.h
- sxt/execution/device/generate.t.cc
- sxt/execution/device/to_device_copier.cc
- sxt/execution/device/to_device_copier.h
- sxt/execution/device/to_device_copier.t.cc
Rework pinned memory buffers and add a to_device_copier where memory can be copied incrementally.
* Reworks pinned_buffer to be easier to use
* Adds a to_device_copier
* Refactors code to use to_device_copier
Yes
> feat: rework pinned memory management (PROOF-928)

- sxt/multiexp/bucket_method/BUILD
- sxt/multiexp/bucket_method/accumulation.h
- sxt/multiexp/bucket_method/fold_kernel.cc
- sxt/multiexp/bucket_method/fold_kernel.h
- sxt/multiexp/bucket_method/fold_kernel.t.cc
- sxt/multiexp/bucket_method/multiexponentiation.t.cc
Batch commitments with elements that are represented in 32-bytes, have 256-384 elements in the sequence, and are the same length will attempt bucket method multiexponention. The bucket method has a max chunk size of `2^20`. In cases where the batch size and element length go above the max chuck size, the commitments are incorrect. For example, `batch_size = 1<<3` and `element_length = 1<<17` will return an expected result, `element_length = 1<<17 + 1` will return an unexpected result. You can see test cases that reproduce the error in commit https://github.com/spaceandtimefdn/blitzar/commit/6d6c2e4a3b1892bf6b220fd9a3a7c6ddcebed7f3.
The issue is the `mtxbk::accumulate_buckets_impl` method. In cases where the number of chunks, `num_chunks`, is greater than 1, the partial bucket sums get …
> fix: multi-chunk batched bucket sums folding error

- benchmark/README.md
- benchmark/scripts/run_benchmarks.py
It would be useful to have a script that was able to run recreate the benchmarks used in the README.md file. This PR adds the script and allows the benchmark suite to run from outside of a NIX development shell with:
```
nix develop --command python3 ./benchmark/scripts/run_benchmarks.py <cpu|gpu>
```
and from inside the NIX development shell with:
```
python3 ./benchmark/scripts/run_benchmarks.py <cpu|gpu>
```
- A python script is added that can run all the benchmarks used to publish results
- The benchmark module's README is updated
Yes
> bench: add benchmark running script that recreates the published benchmarks
